#!/bin/bash
echo "🖼️  OTIMIZADOR DE IMAGENS SIMPLES"
echo "================================="
echo ""
echo "⚠️  ImageMagick não está disponível, mas podemos:"
echo ""
echo "1. ✅ Site já está funcionando sem otimização"
echo "2. ✅ Você pode usar ferramentas online para otimizar imagens:"
echo "   • https://squoosh.app/ (gratuito)"
echo "   • https://tinypng.com/ (gratuito)"
echo "3. ✅ Configure seu servidor para compressão automática"
echo ""
echo "📁 Suas imagens estão em:"
echo "   • assets/images/profile/"
echo "   • assets/images/works/"
echo ""
echo "🎯 Tamanhos recomendados para web:"
echo "   • Perfil: 400x400 pixels, 50-100KB"
echo "   • Trabalhos: 800x600 pixels, 100-200KB"
echo "   • Banner: 1200x400 pixels, 150-300KB"
echo ""
echo "✅ Site já está funcional! Continue desenvolvendo o projeto Cidade de Deus."
